### ISSUE TITLE
Document Story #261, Booking Request Tracking

### ISSUE THREAD

**Issue by KeeganWoods1** [CSU-Booking-Platform/application#281]
### What needs to be done
 

- [x] Create a GitHub Issue using the story template
- [ ] Write acceptance tests
- [x] Create UI mockups
- [ ] Update documentation & design the feature
- [x] Update description to include all relevant info
- [x] Identify possible blockers in other stories.
- [x] Communicate with the team and ask questions

### Out of scope
-NA
