### ISSUE TITLE
Booking Restrictions

### ISSUE THREAD

**Issue by alexstojda** [CSU-Booking-Platform/application#48]
### Documentation Checklist 

- [ ] Domain Model updated
- [ ] Component Diagram updated
- [ ] Class Diagram updated
- [ ] ER Model updated
- [ ] UI Mockups/Prototypes for every groomed story 
- [ ] Mockups are annotated explaining functionality of buttons/inputs/outputs
- [ ] Persona Descriptions updated
- [ ] Mockups for UI Variations based on the personas (where applicable)
- [ ] Show updates to the UI mockups after receiving feedback from product owner
